[build]
  functions = "functions"  # Папка, в которой будут храниться ваши функции AWS Lambda

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/server/send-email"
  status = 200


[dev]
  functionsPort = 3001  # Порт, на котором запускается ваше Express-приложение локально
